const ImageName =
{
	BackgroundTileable:  'backgroundTileable',
    MainPlatformTileset: 'mainPlatformTileset',
    Exit:                'exit',
    Items:               'items',
    Treasure:            'treasure',
    PlayerIdle:          'playerIdle',
    PlayerRunning:       'playerRunning',
    PlayerWalking:       'playerWalking',
    PlayerFalling:       'playerFalling',
    PlayerDucking:       'playerDucking',
    PlayerJumping:       'playerJumping',
    PlayerDoubleJumping: 'playerDoubleJumping',
    PlayerCharging:      'playerCharging',
    PlayerFloating:      'playerFloating',
    PlayerHurting:       'playerHurting',
    PlayerDying:         'playerDying',
    Logo:                'logoBig',
    UiTiles:             'uiTiles',
    PlayerAiming:        'playerAiming',
    PlayerFiring:        'playerFiring',
    PlayerSleeping:      'playerSleeping',
    LogoBig:             'logoBig',
    Gun:                 'gun',
    Bullet:              'bullet',
    BulletEmpty:         'bulletEmpty',
    Heart:               'heart',
    HeartEmpty:          'heartEmpty',
    ChargingUI:          'charging',
    FloatingUI:          'floating',
    AimingUI:            'aiming',
    JumpingUI:           'jumping',
    WalkingLeftUI:       'walkingLeft',
    WalkingRightUI:      'walkingRight',
    DuckingUI:           'ducking',
    Dead:                'playerDead',
    Continue:            'playerDeadContinue',
    Quit:                'playerDeadQuit',
};

export default ImageName;